### ISSUE TITLE
Missing tests_seen and unseen folders in dataset

### ISSUE THREAD

**Issue by anniewernerfelt** [gistvision/moca#7]
I've downloaded the data, but it doesn't seem to have the tests_seen and tests_unseen folders. Can you guide us to where that is?

**Comment by bhkim94** [comment]
Hi @anniewernerfelt,
Sorry for the late reply.

Yes, we didn't upload `tests_seen` and `tests_unseen` because the visual features of the test splits are not public and therefore, we omit the test splits in the Huggingface repo.
Did you fail to run our code because you don't have them? If this is the case, can you share your command so that I can reproduce the error that you got?

Let me know if you have any further issues.
Thanks

**Comment by bhkim94** [comment]
Closed due to inactivity. Feel free to reopen this if you have any further questions.
